link: https://www.petsonic.com/farmacia-para-gatos/
file: z
page_number: 25.0

name_xpath: '//h1[@class = "product_main_name"]/text()'
image_xpath: '//img[@class = "replace-2x img-responsive"]/@src'
variations_xpath: '//div[contains(@class, "attribute_list")]/ul/li'
price_xpath: './/span[@class = "price_comb"]/text()'
weigth_xpath: './/span[@class = "radio_label"]/text()'

number_of_products_xpath: '//input[@id="nb_item_bottom"]/@value'
parsed_product_url_xpath: '//*[@class = "product_img_link pro_img_hover_scale product-list-category-img"]/@href'
